CREATE TABLE KhachHang (
    MaKH VARCHAR(10) PRIMARY KEY,
    TenKH NVARCHAR(100),
    SDT VARCHAR(15),
    DiaChi NVARCHAR(255),
    NoHienTai DECIMAL(12,2) DEFAULT 0,
    VoDangGiu INT DEFAULT 0
);

CREATE TABLE SanPham (
    MaSP VARCHAR(10) PRIMARY KEY,
    TenSP NVARCHAR(100),
    GiaNuoc DECIMAL(10,2),
    GiaVo DECIMAL(10,2)
);

CREATE TABLE HoaDon (
    MaHD VARCHAR(10) PRIMARY KEY,
    NgayLap DATE,
    SoVoKhachTra INT DEFAULT 0,
    DaThanhToan DECIMAL(12,2) DEFAULT 0,
    MaKH VARCHAR(10),

    FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH),
    CONSTRAINT CK_SoVo CHECK (SoVoKhachTra >= 0)
);

CREATE TABLE ChiTietHoaDon (
    MaHD VARCHAR(10),
    MaSP VARCHAR(10),
    SoLuong INT,

    PRIMARY KEY (MaHD, MaSP),

    FOREIGN KEY (MaHD) REFERENCES HoaDon(MaHD),
    FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP),

    CONSTRAINT CK_SoLuong CHECK (SoLuong > 0)
);

CREATE TABLE ThanhToan (
    MaTT VARCHAR(10) PRIMARY KEY,
    NgayThanhToan DATE,
    SoTien DECIMAL(12,2),
    GhiChu NVARCHAR(255),
    MaKH VARCHAR(10),

    FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH),
    CONSTRAINT CK_SoTien CHECK (SoTien > 0)
);